version: '3'

services:
  terraform:
    build: .
    container_name: terraform-container
    working_dir: /app
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    entrypoint: ["/bin/sh"]